from dataclasses import dataclass, field
from typing import List, Optional, Set


@dataclass(frozen=True)
class ContentItem:
    name: str
    category: str
    tags: Set[str]
    # Enhanced optional fields
    park_slugs: List[str] = field(default_factory=list)
    age_groups: List[str] = field(default_factory=list)
    description: str = ""
    seasonal: bool = False


CONTENT_CATALOG: List[ContentItem] = [
    # ------------------------------------------------------------------ Movies
    ContentItem("Frozen", "movie", {"princess", "music", "family", "magic", "ice", "friendship"},
                description="The icy tale of Elsa and Anna in the kingdom of Arendelle.",
                age_groups=["kids", "family"]),
    ContentItem("Frozen II", "movie", {"princess", "music", "family", "magic", "nature", "adventure"},
                description="Elsa journeys to discover the origin of her powers.",
                age_groups=["kids", "family"]),
    ContentItem("Marvel Avengers", "movie", {"hero", "action", "team", "thrill", "sci-fi"},
                description="Earth's mightiest heroes unite against impossible odds.",
                age_groups=["teens", "adults", "family"]),
    ContentItem("Star Wars: The Force Awakens", "movie", {"sci-fi", "action", "adventure", "hero", "space"},
                description="A new generation continues the Skywalker saga.",
                age_groups=["teens", "adults", "family"]),
    ContentItem("The Lion King", "movie", {"family", "music", "adventure", "animals", "nature"},
                description="Simba's journey to reclaim the Pride Lands.",
                age_groups=["kids", "family"]),
    ContentItem("Toy Story", "movie", {"family", "friendship", "animation", "toy", "adventure"},
                description="Woody, Buzz, and the gang come alive when humans aren't watching.",
                age_groups=["kids", "family"]),
    ContentItem("Moana", "movie", {"princess", "ocean", "music", "adventure", "family", "nature"},
                description="A Polynesian girl voyages across the ocean to save her people.",
                age_groups=["kids", "family"]),
    ContentItem("Ratatouille", "movie", {"family", "food", "adventure", "humor", "friendship"},
                description="A rat with culinary dreams conquers a Paris kitchen.",
                age_groups=["kids", "family", "adults"]),
    ContentItem("Zootopia", "movie", {"family", "animals", "adventure", "mystery", "humor"},
                description="A rookie bunny cop and cynical fox solve a big city conspiracy.",
                age_groups=["kids", "family"]),
    ContentItem("Black Panther", "movie", {"hero", "action", "family", "adventure", "tech"},
                description="T'Challa defends Wakanda as king and as Black Panther.",
                age_groups=["teens", "adults", "family"]),
    ContentItem("Encanto", "movie", {"family", "music", "magic", "culture", "friendship"},
                description="A Colombian family each granted a magical gift — except Mirabel.",
                age_groups=["kids", "family"]),
    ContentItem("TRON: Legacy", "movie", {"sci-fi", "thrill", "action", "tech", "music"},
                description="A programmer enters a dangerous digital world built by his father.",
                age_groups=["teens", "adults"]),
    # --------------------------------------------------------------- Characters
    ContentItem("Elsa", "character", {"princess", "magic", "ice", "family"},
                park_slugs=["magic-kingdom", "epcot", "hong-kong-disneyland", "tokyo-disneyland"],
                age_groups=["kids", "family"]),
    ContentItem("Mickey Mouse", "character", {"family", "classic", "magic", "fun"},
                park_slugs=["magic-kingdom", "disneyland", "tokyo-disneyland", "disneyland-paris",
                            "hong-kong-disneyland", "shanghai-disneyland"],
                age_groups=["kids", "family"]),
    ContentItem("Iron Man", "character", {"hero", "tech", "action", "thrill"},
                park_slugs=["hong-kong-disneyland", "disneyland-paris"],
                age_groups=["teens", "adults", "family"]),
    ContentItem("Buzz Lightyear", "character", {"hero", "toy", "space", "family"},
                park_slugs=["magic-kingdom", "disneyland", "tokyo-disneyland", "hong-kong-disneyland"],
                age_groups=["kids", "family"]),
    ContentItem("Moana", "character", {"princess", "ocean", "adventure", "family"},
                park_slugs=["magic-kingdom", "disneyland"],
                age_groups=["kids", "family"]),
    # --------------------------------------------------------------- Merch
    ContentItem("Frozen Castle Doll", "merch", {"princess", "toy", "family", "gift", "ice"},
                age_groups=["kids"]),
    ContentItem("Marvel Action Figure", "merch", {"hero", "toy", "collector", "action"},
                age_groups=["kids", "teens", "adults"]),
    ContentItem("Star Wars Lightsaber", "merch", {"sci-fi", "collector", "action", "space"},
                age_groups=["kids", "teens", "adults"]),
    ContentItem("Mickey Ears Headband", "merch", {"classic", "family", "photo", "gift"},
                age_groups=["kids", "family", "adults"]),
    ContentItem("TRON Collectible Pin", "merch", {"sci-fi", "tech", "collector", "thrill"},
                age_groups=["teens", "adults"]),
    # --------------------------------------------------------- Park experiences
    ContentItem("Pirates Adventure Ride", "park_experience",
                {"adventure", "thrill", "family", "photo"},
                park_slugs=["magic-kingdom", "disneyland", "tokyo-disneyland", "disneyland-paris"],
                description="Sail through pirate battles in this classic boat ride.",
                age_groups=["kids", "family"]),
    ContentItem("Princess Parade", "park_experience",
                {"princess", "music", "photo", "family"},
                park_slugs=["magic-kingdom", "disneyland", "tokyo-disneyland"],
                description="Disney royalty passes by in a dazzling daytime parade.",
                age_groups=["kids", "family"]),
    ContentItem("Star Wars: Galaxy's Edge", "park_experience",
                {"sci-fi", "action", "adventure", "thrill", "space", "immersive"},
                park_slugs=["magic-kingdom", "disneyland", "hollywood-studios"],
                description="A fully immersive Star Wars land with Rise of the Resistance and Smugglers Run.",
                age_groups=["teens", "adults", "family"]),
    ContentItem("Pandora – World of Avatar", "park_experience",
                {"nature", "adventure", "sci-fi", "thrill", "immersive"},
                park_slugs=["animal-kingdom"],
                description="Float over bioluminescent Pandora and soar on a banshee.",
                age_groups=["teens", "adults", "family"]),
    ContentItem("Tokyo DisneySea Fantasy Springs", "park_experience",
                {"princess", "magic", "family", "adventure", "immersive"},
                park_slugs=["tokyo-disneysea"],
                description="Newest expansion featuring Frozen, Tangled, Peter Pan, and Duffy.",
                age_groups=["kids", "family"]),
    ContentItem("Fireworks Night Spectacular", "park_experience",
                {"family", "photo", "music", "classic"},
                park_slugs=["magic-kingdom", "disneyland", "tokyo-disneyland", "disneyland-paris",
                            "hong-kong-disneyland", "shanghai-disneyland"],
                description="Nightly castle fireworks that light up the sky.",
                age_groups=["kids", "family", "adults"]),
    # ------------------------------------------------------- Entertainment
    ContentItem("Fantasmic!", "entertainment",
                {"family", "music", "thrill", "photo", "adventure"},
                park_slugs=["hollywood-studios", "disneyland"],
                description="Mickey's imagination battles Disney villains in a water and fire show.",
                age_groups=["kids", "family"]),
    ContentItem("World of Color", "entertainment",
                {"family", "music", "photo", "magic"},
                park_slugs=["disneyland"],
                description="A breathtaking nighttime water projection show at Disney California Adventure.",
                age_groups=["kids", "family", "adults"]),
    ContentItem("Festival of the Lion King", "entertainment",
                {"family", "music", "animals", "nature"},
                park_slugs=["animal-kingdom"],
                description="An award-winning live stage extravaganza celebrating the Lion King.",
                age_groups=["kids", "family"]),
    # --------------------------------------------------------- Dining
    ContentItem("Be Our Guest Restaurant", "dining",
                {"family", "princess", "magic", "food"},
                park_slugs=["magic-kingdom"],
                description="Dine inside Beast's enchanted castle with French-inspired cuisine.",
                age_groups=["family", "adults"]),
    ContentItem("Oga's Cantina", "dining",
                {"sci-fi", "adults", "action", "adventure"},
                park_slugs=["hollywood-studios", "disneyland"],
                description="A rowdy Star Wars bar serving alien-inspired cocktails.",
                age_groups=["adults", "teens"]),
    ContentItem("Biergarten Restaurant", "dining",
                {"food", "family", "music", "culture"},
                park_slugs=["epcot"],
                description="Bavarian buffet with live oompah band in the Germany Pavilion.",
                age_groups=["adults", "family"]),
]
